// novel-multi-agent service worker (auto-generated by V48 buildServiceWorkerScript)
const CACHE = "novel-ma-v1";
const PRECACHE = ["./","./apps/web/","./apps/tui/","https://yeluo45.github.io/novel-multi-agent/"];
const RUNTIME = ["^https://yeluo45\\.github\\.io/novel-multi-agent/"];
const FALLBACK = "./apps/web/index.html";
self.addEventListener("install", (event) => { event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())); });
self.addEventListener("activate", (event) => { event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  const matches = RUNTIME.some((pattern) => new RegExp(pattern).test(url.href));
  if (!matches) return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      const fetched = fetch(event.request).then((response) => { if (response && response.ok) { const copy = response.clone(); caches.open(CACHE).then((c) => c.put(event.request, copy)); } return response; }).catch(() => cached || caches.match(FALLBACK));
      return cached || fetched;
    })
  );
});